# This file was generated by GoReleaser. DO NOT EDIT.
cask "mysq" do
  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "47a89b1dad6a72240a787685cbb97d7a484d2fd77d9f547582b7707e7d21dc4d"
      url "https://github.com/maheshrijal/mysq/releases/download/v#{version}/mysq_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f5fb917ba884a4f1143d082b27478ffe4a430408983e3c3c9c93eeafe1594065"
      url "https://github.com/maheshrijal/mysq/releases/download/v#{version}/mysq_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9b357261880a725ae8801f3fd576e0d772ee2a3d5a7c6c997faf6c087a6e5640"
      url "https://github.com/maheshrijal/mysq/releases/download/v#{version}/mysq_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "072ea23934732275255fbd84eec2a1f6bef3dddaa381b63bc1eba86347c30f3b"
      url "https://github.com/maheshrijal/mysq/releases/download/v#{version}/mysq_linux_amd64.tar.gz"
    end
  end

  name "mysq"
  desc "Find slow queries, blocked transactions, and MySQL performance problems"
  homepage "https://github.com/maheshrijal/mysq"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mysq"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-d", "com.apple.quarantine", "#{staged_path}/mysq"]
    end
  end

  # No zap stanza required
end
