# This file was generated by GoReleaser. DO NOT EDIT.
cask "zocli" do
  name "zocli"
  desc "Unofficial Zomato order tracker CLI"
  homepage "https://github.com/maheshrijal/zocli"
  version "0.1.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zocli"

  on_macos do
    on_intel do
      url "https://github.com/maheshrijal/zocli/releases/download/v#{version}/zocli_#{version}_darwin_amd64.tar.gz"
      sha256 "254a5a1b9f89590987330cc74ee86892d510bb224de89e4841c64a652ab7f664"
    end
    on_arm do
      url "https://github.com/maheshrijal/zocli/releases/download/v#{version}/zocli_#{version}_darwin_arm64.tar.gz"
      sha256 "42d4098cd76f128103d2621eba21ea52dd51c240af78f0ab783f5cf715a42365"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/maheshrijal/zocli/releases/download/v#{version}/zocli_#{version}_linux_amd64.tar.gz"
      sha256 "ff0f76ead0afa21988d44769254f41fc737b88df70bf2048b4e997734f3d2dc7"
    end
    on_arm do
      url "https://github.com/maheshrijal/zocli/releases/download/v#{version}/zocli_#{version}_linux_arm64.tar.gz"
      sha256 "301218a87ba106765f68fed6c25ea17919e47dd6f6074f7412cd99e3db69eef7"
    end
  end

  # No zap stanza required
end
