# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zocli < Formula
  desc "Unofficial Zomato order tracker CLI"
  homepage "https://github.com/maheshrijal/zocli"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/maheshrijal/zocli/releases/download/v0.1.3/zocli_0.1.3_darwin_amd64.tar.gz"
      sha256 "ec2374b77a5711edb72ddbd8fd55e2f566704ba84c4077cf69bc37fd805b84d5"

      def install
        bin.install "zocli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/maheshrijal/zocli/releases/download/v0.1.3/zocli_0.1.3_darwin_arm64.tar.gz"
      sha256 "3ab734af8b5b04699d491d38a629885320541f22908339e41efa779a61d2b519"

      def install
        bin.install "zocli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/maheshrijal/zocli/releases/download/v0.1.3/zocli_0.1.3_linux_amd64.tar.gz"
      sha256 "79293d22f671c4d59a81f1bfab8a3b954786e1ae645d2470f5dafe0ab029addc"
      def install
        bin.install "zocli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/maheshrijal/zocli/releases/download/v0.1.3/zocli_0.1.3_linux_arm64.tar.gz"
      sha256 "b337caff35b402d96143fc33126b4e1ce60808bf81d43bf42f7d66107a662807"
      def install
        bin.install "zocli"
      end
    end
  end

  test do
    system "#{bin}/zocli", "version"
  end
end
