# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bislericli < Formula
  desc "Unofficial Bisleri order tracker CLI"
  homepage "https://github.com/maheshrijal/bislericli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/maheshrijal/bislericli/releases/download/v0.1.0/bislericli_0.1.0_darwin_amd64.tar.gz"
      sha256 "b4313a0d6fee365ea92885611012929d0d85be035a02098b92d2beae5585c631"

      def install
        bin.install "bislericli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/maheshrijal/bislericli/releases/download/v0.1.0/bislericli_0.1.0_darwin_arm64.tar.gz"
      sha256 "730558cf67ccab1e4c0029fa3cbc2a386a2ad93be7633f59e32fa0708b472809"

      def install
        bin.install "bislericli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/maheshrijal/bislericli/releases/download/v0.1.0/bislericli_0.1.0_linux_amd64.tar.gz"
      sha256 "09e9aa780d0c0424fe9dec6001dd6daf7a1d3a3c6e3600b25b7c189944716c3f"
      def install
        bin.install "bislericli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/maheshrijal/bislericli/releases/download/v0.1.0/bislericli_0.1.0_linux_arm64.tar.gz"
      sha256 "39f1d30df73287f1e9fccfa6e34ef2e3042c3765001b850a7a8ab5128a36d067"
      def install
        bin.install "bislericli"
      end
    end
  end

  test do
    system "#{bin}/bislericli", "version"
  end
end
