# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bislericli < Formula
  desc "Unofficial Bisleri order tracker CLI"
  homepage "https://github.com/maheshrijal/bislericli"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/maheshrijal/bislericli/releases/download/v0.1.3/bislericli_0.1.3_darwin_amd64.tar.gz"
      sha256 "e565dc55b5e778eefc5dc6336c9d538b7dbd276262005ebaeabe627daa7537e9"

      define_method(:install) do
        bin.install "bislericli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/maheshrijal/bislericli/releases/download/v0.1.3/bislericli_0.1.3_darwin_arm64.tar.gz"
      sha256 "7ee79e2a8bc624feafd11cb692bc0e88687de5335d09b3847f110a5cda8f1817"

      define_method(:install) do
        bin.install "bislericli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/maheshrijal/bislericli/releases/download/v0.1.3/bislericli_0.1.3_linux_amd64.tar.gz"
      sha256 "30dfe4c95a9a9877609d5d729cef1348aaf38e6f3e1e7e25f8da6e0a78eebd61"
      define_method(:install) do
        bin.install "bislericli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/maheshrijal/bislericli/releases/download/v0.1.3/bislericli_0.1.3_linux_arm64.tar.gz"
      sha256 "b678d1aaffcc4695b98a7b344964ee0bc0ba84f6ed90e9de0b8e3d69ca153dd8"
      define_method(:install) do
        bin.install "bislericli"
      end
    end
  end

  test do
    system "#{bin}/bislericli", "version"
  end
end
