# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Blinkcli < Formula
  desc "Unofficial Blinkit order tracker CLI"
  homepage "https://github.com/maheshrijal/blinkcli"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/maheshrijal/blinkcli/releases/download/v0.1.4/blinkcli_0.1.4_darwin_amd64.tar.gz"
      sha256 "33896ad79e2a9b9366515cd6c18ea2fb59fef504aa83f909f9fd704f30dd7fac"

      def install
        bin.install "blinkcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/maheshrijal/blinkcli/releases/download/v0.1.4/blinkcli_0.1.4_darwin_arm64.tar.gz"
      sha256 "65f79896a8325b3940dbc28bafd3ee968e4c4c37e280961e15971be95bd15920"

      def install
        bin.install "blinkcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/maheshrijal/blinkcli/releases/download/v0.1.4/blinkcli_0.1.4_linux_amd64.tar.gz"
      sha256 "eda453f55af76968efdcbbfc4aca9295b805ef402cc2966f2c803bb166fa204f"
      def install
        bin.install "blinkcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/maheshrijal/blinkcli/releases/download/v0.1.4/blinkcli_0.1.4_linux_arm64.tar.gz"
      sha256 "d00c6b17b4a3ec1431480f9709ec2365e3c131164437ab85b0de7a0d3d9a2811"
      def install
        bin.install "blinkcli"
      end
    end
  end

  test do
    system "#{bin}/blinkcli", "version"
  end
end
