# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Blinkcli < Formula
  desc "Unofficial Blinkit order tracker CLI"
  homepage "https://github.com/maheshrijal/blinkcli"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/maheshrijal/blinkcli/releases/download/v0.1.2/blinkcli_0.1.2_darwin_amd64.tar.gz"
      sha256 "4e33670e547460532119400cc2801ca0da3f48c0ecc012a5ef4273ba3029fd7e"

      def install
        bin.install "blinkcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/maheshrijal/blinkcli/releases/download/v0.1.2/blinkcli_0.1.2_darwin_arm64.tar.gz"
      sha256 "90e34dd4433506ff5ccfeb27619945169c388d6ebb6a17f06691ccf2811a5216"

      def install
        bin.install "blinkcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/maheshrijal/blinkcli/releases/download/v0.1.2/blinkcli_0.1.2_linux_amd64.tar.gz"
      sha256 "1e63a23bd8b7fd2a4111698cadff0e23f97773acdd811ce3d009006f322c87f6"
      def install
        bin.install "blinkcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/maheshrijal/blinkcli/releases/download/v0.1.2/blinkcli_0.1.2_linux_arm64.tar.gz"
      sha256 "bf9e74337f0eb019e68741a23617a83d46f6651ba2b955bea778f6a3506cd3e5"
      def install
        bin.install "blinkcli"
      end
    end
  end

  test do
    system "#{bin}/blinkcli", "version"
  end
end
