# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Blinkcli < Formula
  desc "Unofficial Blinkit order tracker CLI"
  homepage "https://github.com/maheshrijal/blinkcli"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/maheshrijal/blinkcli/releases/download/v0.1.1/blinkcli_0.1.1_darwin_amd64.tar.gz"
      sha256 "8f23eb1f3650e04fcc7d72f72bbe572f3a8f78a8c529ed77444e81b8508b97f5"

      def install
        bin.install "blinkcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/maheshrijal/blinkcli/releases/download/v0.1.1/blinkcli_0.1.1_darwin_arm64.tar.gz"
      sha256 "275fcdae5e6bd6e84bc728529621ecd282986c7efc3eb42b69da3528e72c85f9"

      def install
        bin.install "blinkcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/maheshrijal/blinkcli/releases/download/v0.1.1/blinkcli_0.1.1_linux_amd64.tar.gz"
      sha256 "07d6bb42335be184045fab6490574764b425f192fb0a2726b64949c81d5f27d4"
      def install
        bin.install "blinkcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/maheshrijal/blinkcli/releases/download/v0.1.1/blinkcli_0.1.1_linux_arm64.tar.gz"
      sha256 "4b850cb80f9c24fabcc39723076dbeb74447f1ee2a419a11f6a6e92e16eced3f"
      def install
        bin.install "blinkcli"
      end
    end
  end

  test do
    system "#{bin}/blinkcli", "version"
  end
end
