# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zocli < Formula
  desc "Unofficial Zomato order tracker CLI"
  homepage "https://github.com/maheshrijal/zocli"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/maheshrijal/zocli/releases/download/v0.1.1/zocli_0.1.1_darwin_amd64.tar.gz"
      sha256 "c2b8343ca182f760d703b55fa888273835023cf6f1434f61ed2f2518d0bdaa4c"

      def install
        bin.install "zocli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/maheshrijal/zocli/releases/download/v0.1.1/zocli_0.1.1_darwin_arm64.tar.gz"
      sha256 "83113daf53294f707ae73ca85efb213ba0788d4bdfbb6e602c038c1fa45b84ae"

      def install
        bin.install "zocli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/maheshrijal/zocli/releases/download/v0.1.1/zocli_0.1.1_linux_amd64.tar.gz"
      sha256 "a72d8708b5556eb00f5303b101dffc354904bf4a74727c317c268f18cd6ab892"
      def install
        bin.install "zocli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/maheshrijal/zocli/releases/download/v0.1.1/zocli_0.1.1_linux_arm64.tar.gz"
      sha256 "199336c8525a14f6fecbc08e1de5bd0f7cbdc123d33b69e933e5253dc186f654"
      def install
        bin.install "zocli"
      end
    end
  end

  test do
    system "#{bin}/zocli", "version"
  end
end
