# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zocli < Formula
  desc "Unofficial Zomato order tracker CLI"
  homepage "https://github.com/maheshrijal/zocli"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/maheshrijal/zocli/releases/download/v0.1.2/zocli_0.1.2_darwin_amd64.tar.gz"
      sha256 "2c8469037bac3cfe306afb28926182ce727b98805094083d2a479cc1fd90f83c"

      def install
        bin.install "zocli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/maheshrijal/zocli/releases/download/v0.1.2/zocli_0.1.2_darwin_arm64.tar.gz"
      sha256 "29a982fe360d2937c910321bee3e258f11d7bc7796d396b5a06d22f4d4f33ee8"

      def install
        bin.install "zocli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/maheshrijal/zocli/releases/download/v0.1.2/zocli_0.1.2_linux_amd64.tar.gz"
      sha256 "8e5230771fd8f19ab8916a40fce99eaab26d8f8f7fe659bdcd9eb96bb8ddcdf2"
      def install
        bin.install "zocli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/maheshrijal/zocli/releases/download/v0.1.2/zocli_0.1.2_linux_arm64.tar.gz"
      sha256 "495c37f209312ad7bc9ff6087819952736dca48f5c6874a0a3712c3e9fc8bf04"
      def install
        bin.install "zocli"
      end
    end
  end

  test do
    system "#{bin}/zocli", "version"
  end
end
