# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zocli < Formula
  desc "Unofficial Zomato order tracker CLI"
  homepage "https://github.com/maheshrijal/zocli"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/maheshrijal/zocli/releases/download/v0.1.6/zocli_0.1.6_darwin_amd64.tar.gz"
      sha256 "b2281225c565bd62958669dda1da8801f68970aadf779134e65eec7a9506ca4f"

      def install
        bin.install "zocli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/maheshrijal/zocli/releases/download/v0.1.6/zocli_0.1.6_darwin_arm64.tar.gz"
      sha256 "1d0602f8c34fec094e7edab9b41818e8166680dd2488d2196eb08bf9ccf1a4de"

      def install
        bin.install "zocli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/maheshrijal/zocli/releases/download/v0.1.6/zocli_0.1.6_linux_amd64.tar.gz"
      sha256 "0c552e06c4234115ee53a6f3d5c0f76252813194c4fd9743542278bb52058108"
      def install
        bin.install "zocli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/maheshrijal/zocli/releases/download/v0.1.6/zocli_0.1.6_linux_arm64.tar.gz"
      sha256 "e189d76b7664ed4c27b5188a68b82a98e3be92291646ba5c9244d3b0f82006bb"
      def install
        bin.install "zocli"
      end
    end
  end

  test do
    system "#{bin}/zocli", "version"
  end
end
